#!/usr/bin/env ruby

if $*.empty?
  puts "\n\tdehal.rb [header files...]\n"
  exit 1
end

vars = [*('a'..'z')]
$*.each do |f|
  next unless File.file? f and f[-2..-1] == '.h'
  File.open("#{f[0..-3]}_dehal.h", "w") do |fh|
    m = "#{f[0..-3].upcase}_H_DEHAL"
    fh.write "// Generated by dehal.rb\n"
    fh.write "#ifndef #{m}\n"
    fh.write "#define #{m}\n"
    `ctags -x --c-kinds=fp --sort=no #{f}`.split("\n").each do |p|
      /^hal_(?<name>[a-zA-Z0-9_-]+)\s+prototype\s+\d+\s+\S+\s+\s+\*?\S+\*?\s+hal_\S+\((?<function>.*)\);$/ =~ p
      v = vars[0..function.split(',').length]
      fh.write "#define #{name}(#{v.join(', ')}) hal_#{name}(#{v.map{|s|"(#{s})"}.join(', ')})\n"
    end
    fh.write "#endif // #{m}\n"
  end
end

