#!/usr/bin/env ruby

# Test arguments
if $*.length < 2
  puts "\n\tsplit_sh.rb [header file] [implementation macro]\n\n"
  exit 1
end

(0..$*.length-2).each do |i|
  unless File.file? $*[i] and $*[i][-2..-1] == '.h'
    puts "#{$*[i]} doesn't exist or isn't a valid file"
    next
  end

  # Parse the file
  ll, ls, le = [], 0, 0
  File.readlines($*[i]).each_with_index do |l, i|
    ll.push l
    ls = i if l =~ /^#if #{$*[-1]}_IMPLEMENTATION$/ or l =~ /^#if defined\(#{$*[-1]}_IMPLEMENTATION\)$/
    le = i if l =~/^#endif \/\/ #{$*[-1]}_IMPLEMENTATION$/
  end
  if not ls or not le or ls + 1 == le
    puts "#{$*[i]} has nothing to split"
    next
  end

  # Write the outputs
  File.write 'hal_' + $*[i][0..-3] + '.c', (["// Generated by split_sh.rb\n#include \"hal_#{$*[i]}\"\n"] + ll.slice!(ls..le)[1..-2]) * ''
  File.write 'hal_' + $*[i], ll * ''
end

